### ISSUE TITLE
为什么LuaClient.cs中的OpenLibs函数里的pb改成了pb2？

### ISSUE THREAD

**Issue by jozhn** [NewbieGameCoder/tolua#38]
```c#
luaState.AddPreLoadLib("pb2", new LuaCSFunction(LuaDLL.luaopen_pb));
```

我替换protoc-gen-lua为lua-protobuf之后，安卓下AddPreLoadLib会失败。
请教一下为什么这样改呢？

**Comment by NewbieGameCoder** [comment]
作者可能还是为了兼容lua-protobuf的pb3，避免tolua的protobuf.lua引用到了错误的protobuf版本（这个lua文件只能用pb2好像）

**Comment by NewbieGameCoder** [comment]
现在会报错，方便替换成pb3的人迁移
